version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media/
    depends_on:
      - web
  db:
    image: mysql:5.7
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gel2mdt_db
      - MYSQL_USER=paddy
      - MYSQL_PASSWORD=password
    volumes:
       - /var/lib/mysql
  redis:
    image: "redis:alpine"

  web:
    build: .
    # command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    container_name: example_django
    command: bash -c "python /code/manage.py migrate --noinput && gunicorn test_ap.wsgi -b 0.0.0.0:8000"
    environment:
      UTA_DB_URL: postgresql://anonymous@localhost:5432/uta/uta_20171026
    volumes:
      - .:/code
      - ./static:/static
      - ./media:/media/
    depends_on:
      - db
      - redis

  hgvs:
    image: biocommons/uta:uta_20171026
    env_file: env_vars.txt
    network_mode: host

  celery:
    build: .
    command: celery -A test_ap worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A test_ap beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      - PMA_ARBITRARY=1
#    restart: always
#    ports:
#      - 8082:80
#    volumes:
#      - /sessions
